set PATH=%PATH%;%LIB_DIR%\swigwin-4.3.0
set PYTHON_LIB=C:\Users\Usuario\AppData\Local\Programs\Python\Python313

cmake ..\WeldFormGUI -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=RELEASE ^
-DVTK_INCLUDE_DIR=%LIB_DIR%\vtk-9.3.1_install -DVTK_MODULE_ENABLE_VTK_IOOCCT=ON ^
-DCMAKE_PREFIX_PATH=%LIB_DIR%\OCCT\cmake ^
-DVTK_MODULE_ENABLE_VTK_IOOCCT=ON ^
-DPYTHON_INCLUDE_DIRS=%PYTHON_LIB%\include ^
-DPYTHON_LIBRARY=%PYTHON_LIB%\libs\python313.lib ^
-DPYTHON_LIBRARY_DEBUG=%PYTHON_LIB%\libs\python313.lib ^
-DOpenCASCADE_DIR=%LIB_DIR%\OCCT_7.8.0\occt-vc143-64\cmake ^
-DBUILD_PYTHON=OFF