
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Compilador de optimización de C/C++ de Microsoft (R) versión 19.29.30159 para x64
      (C) Microsoft Corporation. Todos los derechos reservados.
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.29.30159.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        D:/Luciano/Numerico/WeldFormGUI/CMakeFiles/4.0.2/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1322 (message)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        Nota: inclusión del archivo: D:\\Luciano\\Numerico\\WeldFormGUI\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Nota: inclusión del archivo: "
  -
    kind: "message-v1"
    backtrace:
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Compilador de optimización de C/C++ de Microsoft (R) versión 19.29.30159 para x64
      (C) Microsoft Corporation. Todos los derechos reservados.
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.29.30159.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        D:/Luciano/Numerico/WeldFormGUI/CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1322 (message)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        Nota: inclusión del archivo: D:\\Luciano\\Numerico\\WeldFormGUI\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Nota: inclusión del archivo: "
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/Luciano/Numerico/WeldFormGUI/CMakeFiles/CMakeScratch/TryCompile-4l2hyc"
      binary: "D:/Luciano/Numerico/WeldFormGUI/CMakeFiles/CMakeScratch/TryCompile-4l2hyc"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Luciano/Numerico/WeldFormGUI/CMakeFiles/CMakeScratch/TryCompile-4l2hyc'
        
        Run Build Command(s): D:/Luciano/Programas/cmake-4.0.2/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_afb00\\fast
        	"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_afb00.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_afb00.dir\\build
        Building C object CMakeFiles/cmTC_afb00.dir/CMakeCCompilerABI.c.obj
        	D:\\Luciano\\Programas\\cmake-4.0.2\\bin\\cmake.exe -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_afb00.dir\\CMakeCCompilerABI.c.obj.d --working-dir=D:\\Luciano\\Numerico\\WeldFormGUI\\CMakeFiles\\CMakeScratch\\TryCompile-4l2hyc --filter-prefix="Nota: inclusi¾n del archivo: " -- C:\\PROGRA~2\\MICROS~2\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\Usuario\\AppData\\Local\\Temp\\nmE6A5.tmp
        CMakeCCompilerABI.c
        Linking C executable cmTC_afb00.exe
        	D:\\Luciano\\Programas\\cmake-4.0.2\\bin\\cmake.exe -E vs_link_exe --msvc-ver=1929 --intdir=CMakeFiles\\cmTC_afb00.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe --manifests -- C:\\PROGRA~2\\MICROS~2\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_afb00.dir\\objects1.rsp @C:\\Users\\Usuario\\AppData\\Local\\Temp\\nmE713.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_afb00.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_afb00.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_afb00.dir/manifest.res CMakeFiles\\cmTC_afb00.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~2\\MICROS~2\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_afb00.dir\\objects1.rsp /out:cmTC_afb00.exe /implib:cmTC_afb00.lib /pdb:D:\\Luciano\\Numerico\\WeldFormGUI\\CMakeFiles\\CMakeScratch\\TryCompile-4l2hyc\\cmTC_afb00.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_afb00.dir/intermediate.manifest CMakeFiles\\cmTC_afb00.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_afb00.dir/intermediate.manifest /out:CMakeFiles\\cmTC_afb00.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_afb00.dir/manifest.res CMakeFiles\\cmTC_afb00.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~2\\MICROS~2\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_afb00.dir\\objects1.rsp /out:cmTC_afb00.exe /implib:cmTC_afb00.lib /pdb:D:\\Luciano\\Numerico\\WeldFormGUI\\CMakeFiles\\CMakeScratch\\TryCompile-4l2hyc\\cmTC_afb00.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_afb00.dir/intermediate.manifest CMakeFiles\\cmTC_afb00.dir/manifest.res
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:227 (message)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'C': C:/PROGRA~2/MICROS~2/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301/bin/Hostx64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/Internal/CMakeDetermineLinkerId.cmake:36 (message)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:270 (cmake_determine_linker_id)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the C compiler's linker: "C:/PROGRA~2/MICROS~2/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301/bin/Hostx64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.29.30159.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/Luciano/Numerico/WeldFormGUI/CMakeFiles/CMakeScratch/TryCompile-q700wg"
      binary: "D:/Luciano/Numerico/WeldFormGUI/CMakeFiles/CMakeScratch/TryCompile-q700wg"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Luciano/Numerico/WeldFormGUI/CMakeFiles/CMakeScratch/TryCompile-q700wg'
        
        Run Build Command(s): D:/Luciano/Programas/cmake-4.0.2/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_70495\\fast
        	"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_70495.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_70495.dir\\build
        Building CXX object CMakeFiles/cmTC_70495.dir/CMakeCXXCompilerABI.cpp.obj
        	D:\\Luciano\\Programas\\cmake-4.0.2\\bin\\cmake.exe -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_70495.dir\\CMakeCXXCompilerABI.cpp.obj.d --working-dir=D:\\Luciano\\Numerico\\WeldFormGUI\\CMakeFiles\\CMakeScratch\\TryCompile-q700wg --filter-prefix="Nota: inclusi¾n del archivo: " -- C:\\PROGRA~2\\MICROS~2\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\Usuario\\AppData\\Local\\Temp\\nmE9B2.tmp
        CMakeCXXCompilerABI.cpp
        Linking CXX executable cmTC_70495.exe
        	D:\\Luciano\\Programas\\cmake-4.0.2\\bin\\cmake.exe -E vs_link_exe --msvc-ver=1929 --intdir=CMakeFiles\\cmTC_70495.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe --manifests -- C:\\PROGRA~2\\MICROS~2\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_70495.dir\\objects1.rsp @C:\\Users\\Usuario\\AppData\\Local\\Temp\\nmEA20.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_70495.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_70495.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_70495.dir/manifest.res CMakeFiles\\cmTC_70495.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~2\\MICROS~2\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_70495.dir\\objects1.rsp /out:cmTC_70495.exe /implib:cmTC_70495.lib /pdb:D:\\Luciano\\Numerico\\WeldFormGUI\\CMakeFiles\\CMakeScratch\\TryCompile-q700wg\\cmTC_70495.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_70495.dir/intermediate.manifest CMakeFiles\\cmTC_70495.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_70495.dir/intermediate.manifest /out:CMakeFiles\\cmTC_70495.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100190~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_70495.dir/manifest.res CMakeFiles\\cmTC_70495.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~2\\MICROS~2\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1429~1.301\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_70495.dir\\objects1.rsp /out:cmTC_70495.exe /implib:cmTC_70495.lib /pdb:D:\\Luciano\\Numerico\\WeldFormGUI\\CMakeFiles\\CMakeScratch\\TryCompile-q700wg\\cmTC_70495.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_70495.dir/intermediate.manifest CMakeFiles\\cmTC_70495.dir/manifest.res
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:227 (message)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': C:/PROGRA~2/MICROS~2/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301/bin/Hostx64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/Internal/CMakeDetermineLinkerId.cmake:36 (message)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:270 (cmake_determine_linker_id)"
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the CXX compiler's linker: "C:/PROGRA~2/MICROS~2/2019/COMMUN~1/VC/Tools/MSVC/1429~1.301/bin/Hostx64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.29.30159.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
