
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Luciano/Programas/cmake-4.0.2/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
