from model import *

import os


# Set this to an explicit path if you do not want the default "<model>.inp".
DEFAULT_OUTPUT_PATH = None


PLANE_STRESS_2D = 0
PLANE_STRAIN_2D = 1
AXISYMMETRIC_2D = 2
SOLID_3D = 3
APPLY_TO_PART = 0
APPLY_TO_NODE_SET = 1

VELOCITY_BC = 0
DISPLACEMENT_BC = 1
SYMMETRY_BC = 2


def _safe_part_name(part, fallback_index):
    name = part.getName()
    if name:
        cleaned = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name.strip())
        if cleaned:
            return cleaned
    return f"Part_{fallback_index}"


def _safe_set_name(node_set, fallback_index):
    label = node_set.getLabel()
    if label:
        cleaned = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in label.strip())
        if cleaned:
            return cleaned
    return f"NodeSet_{fallback_index}"


def _default_output_path(model):
    model_path = ""
    try:
        model_path = model.getFilePath()
    except Exception:
        model_path = ""

    if model_path:
        stem, _ = os.path.splitext(model_path)
        return stem + ".inp"

    model_name = model.getName() or "model"
    stem, _ = os.path.splitext(model_name)
    if not stem:
        stem = "model"
    return os.path.abspath(stem + ".inp")


def _active_dofs_for_analysis(model):
    analysis_type = model.getAnalysisType()
    if analysis_type == SOLID_3D:
        return [1, 2, 3]
    return [1, 2]


def _component_values(value):
    return [value[0], value[1], value[2]]


def _bc_value_components(bc):
    try:
        return [bc.getValueX(), bc.getValueY(), bc.getValueZ()]
    except AttributeError:
        value = bc.getValue()
        return _component_values(value)


def _normal_components(bc):
    try:
        return [bc.getNormalX(), bc.getNormalY(), bc.getNormalZ()]
    except AttributeError:
        normal = bc.getNormal()
        return [normal.x, normal.y, normal.z]


def _dofs_from_value(model, value):
    active_dofs = _active_dofs_for_analysis(model)
    components = _component_values(value)
    selected = [dof for dof in active_dofs if abs(components[dof - 1]) > 0.0]
    if selected:
        return selected
    return active_dofs


def _dofs_from_bc(model, bc):
    active_dofs = _active_dofs_for_analysis(model)

    try:
        mask = [bc.getDofMaskX(), bc.getDofMaskY(), bc.getDofMaskZ()]
        selected = [dof for dof in active_dofs if mask[dof - 1]]
        if selected:
            return selected
    except AttributeError:
        pass

    class _ValueProxy:
        def __init__(self, components):
            self._components = components

        def __getitem__(self, index):
            return self._components[index]

    return _dofs_from_value(model, _ValueProxy(_bc_value_components(bc)))


def _symmetry_keyword(model, normal):
    nx = abs(normal[0])
    ny = abs(normal[1])
    nz = abs(normal[2])
    tol = 1.0e-8

    if model.getAnalysisType() == SOLID_3D:
        if nx > 1.0 - tol and ny < tol and nz < tol:
            return "XSYMM"
        if ny > 1.0 - tol and nx < tol and nz < tol:
            return "YSYMM"
        if nz > 1.0 - tol and nx < tol and ny < tol:
            return "ZSYMM"
        return None

    if nx > 1.0 - tol and ny < tol:
        return "XSYMM"
    if ny > 1.0 - tol and nx < tol:
        return "YSYMM"
    return None


def _element_type_for_part(model, mesh, node_count):
    analysis_type = model.getAnalysisType()
    mesh_dim = mesh.getDim()

    if node_count == 2:
        return "T2D2" if mesh_dim == 2 else "T3D2"

    if analysis_type == PLANE_STRESS_2D:
        if node_count == 3:
            return "CPS3"
        if node_count == 4:
            return "CPS4"
    elif analysis_type == PLANE_STRAIN_2D:
        if node_count == 3:
            return "CPE3"
        if node_count == 4:
            return "CPE4"
    elif analysis_type == AXISYMMETRIC_2D:
        if node_count == 3:
            return "CAX3"
        if node_count == 4:
            return "CAX4"
    else:
        if node_count == 4:
            return "C3D4"
        if node_count == 6:
            return "C3D6"
        if node_count == 8:
            return "C3D8"

    raise ValueError(
        f"Unsupported Abaqus element mapping: analysisType={analysis_type}, "
        f"meshDim={mesh_dim}, nodesPerElement={node_count}"
    )


def export_model_to_abaqus(model, output_path):
    if model is None:
        raise RuntimeError("No active model available")

    output_path = os.path.abspath(output_path)
    output_dir = os.path.dirname(output_path)
    if output_dir and not os.path.isdir(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    with open(output_path, "w", encoding="ascii") as out:
        out.write("*HEADING\n")
        out.write("WeldFormGUI export to Abaqus\n")
        out.write("** Generated by scripts/export_abaqus.py\n")

        exported_part_names = []
        part_records = []

        for part_index in range(model.getPartCount()):
            part = model.getPart(part_index)
            if part is None or part.getMesh() is None:
                continue

            mesh = part.getMesh()
            part_name = _safe_part_name(part, part_index)
            exported_part_names.append(part_name)
            instance_name = f"{part_name}-1"

            out.write(f"**\n** PART: {part_name}\n**\n")
            out.write(f"*PART, NAME={part_name}\n")
            out.write("*NODE\n")

            node_label_by_id = {}
            for node_index in range(mesh.getNodeCount()):
                node = mesh.getNode(node_index)
                label = node_index + 1
                node_label_by_id[node.getId()] = label
                out.write(
                    f"{label}, {node.getPos(0):.16g}, {node.getPos(1):.16g}, {node.getPos(2):.16g}\n"
                )

            elements_by_type = {}
            for elem_index in range(mesh.getElemCount()):
                elem = mesh.getElem(elem_index)
                elem_type = _element_type_for_part(model, mesh, elem.getNodeCount())
                connectivity = []
                for local_node in range(elem.getNodeCount()):
                    node_id = elem.getNodeId(local_node)
                    if node_id not in node_label_by_id:
                        raise KeyError(
                            f"Element {elem_index + 1} references unknown node id {node_id}"
                        )
                    connectivity.append(node_label_by_id[node_id])
                elements_by_type.setdefault(elem_type, []).append((elem_index + 1, connectivity))

            for elem_type, elements in elements_by_type.items():
                out.write(f"*ELEMENT, TYPE={elem_type}\n")
                for elem_label, connectivity in elements:
                    conn_str = ", ".join(str(value) for value in connectivity)
                    out.write(f"{elem_label}, {conn_str}\n")

            out.write("*NSET, NSET=ALL_NODES\n")
            all_labels = list(range(1, mesh.getNodeCount() + 1))
            for start in range(0, len(all_labels), 16):
                chunk = all_labels[start:start + 16]
                out.write(", ".join(str(value) for value in chunk) + "\n")

            node_set_names_by_id = {}
            for set_index in range(mesh.getNodeSetCount()):
                node_set = mesh.getNodeSet(set_index)
                set_name = _safe_set_name(node_set, set_index)
                node_set_names_by_id[node_set.getId()] = set_name
                labels = []
                for item_index in range(node_set.getItemCount()):
                    node = node_set.getItem(item_index)
                    node_id = node.getId()
                    if node_id not in node_label_by_id:
                        raise KeyError(
                            f"NodeSet {set_name} references unknown node id {node_id}"
                        )
                    labels.append(node_label_by_id[node_id])

                out.write(f"*NSET, NSET={set_name}\n")
                for start in range(0, len(labels), 16):
                    chunk = labels[start:start + 16]
                    out.write(", ".join(str(value) for value in chunk) + "\n")

            out.write("*END PART\n")
            part_records.append(
                {
                    "part": part,
                    "part_id": part.getId(),
                    "part_name": part_name,
                    "instance_name": instance_name,
                    "node_set_names_by_id": node_set_names_by_id,
                }
            )

        out.write("**\n** ASSEMBLY\n**\n")
        out.write("*ASSEMBLY, NAME=Assembly\n")
        for part_name in exported_part_names:
            out.write(f"*INSTANCE, NAME={part_name}-1, PART={part_name}\n")
            out.write("*END INSTANCE\n")
        out.write("*END ASSEMBLY\n")

        if model.getBCCount() > 0:
            out.write("**\n** BOUNDARY CONDITIONS\n**\n")

        part_record_by_id = {record["part_id"]: record for record in part_records}
        node_set_record_by_id = {}
        for record in part_records:
            for set_id, set_name in record["node_set_names_by_id"].items():
                node_set_record_by_id[set_id] = (record, set_name)

        for bc_index in range(model.getBCCount()):
            bc = model.getBC(bc_index)
            if bc is None:
                continue

            target_name = None
            if bc.getApplyTo() == APPLY_TO_PART:
                record = part_record_by_id.get(bc.getTargetId())
                if record is None:
                    out.write(f"** Skipping BC {bc_index}: missing part target {bc.getTargetId()}\n")
                    continue
                target_name = f"{record['instance_name']}.ALL_NODES"
            elif bc.getApplyTo() == APPLY_TO_NODE_SET:
                node_set_record = node_set_record_by_id.get(bc.getTargetId())
                if node_set_record is None:
                    out.write(f"** Skipping BC {bc_index}: missing node set target {bc.getTargetId()}\n")
                    continue
                record, set_name = node_set_record
                target_name = f"{record['instance_name']}.{set_name}"
            else:
                out.write(f"** Skipping BC {bc_index}: unsupported applyTo={bc.getApplyTo()}\n")
                continue

            bc_type = bc.getType()
            value_components = _bc_value_components(bc)

            if bc_type == DISPLACEMENT_BC:
                out.write("*BOUNDARY, TYPE=DISPLACEMENT\n")
                for dof in _dofs_from_bc(model, bc):
                    component_value = value_components[dof - 1]
                    out.write(f"{target_name}, {dof}, {dof}, {component_value:.16g}\n")
            elif bc_type == VELOCITY_BC:
                out.write("*BOUNDARY, TYPE=VELOCITY\n")
                for dof in _dofs_from_bc(model, bc):
                    component_value = value_components[dof - 1]
                    out.write(f"{target_name}, {dof}, {dof}, {component_value:.16g}\n")
            elif bc_type == SYMMETRY_BC:
                normal_components = _normal_components(bc)
                symmetry = _symmetry_keyword(model, normal_components)
                if symmetry is None:
                    out.write(
                        f"** Skipping BC {bc_index}: unsupported symmetry normal "
                        f"({normal_components[0]:.16g}, {normal_components[1]:.16g}, {normal_components[2]:.16g})\n"
                    )
                    continue
                out.write("*BOUNDARY\n")
                out.write(f"{target_name}, {symmetry}\n")
            else:
                out.write(f"** Skipping BC {bc_index}: unsupported BC type {bc_type}\n")

    print(f"Abaqus export written to: {output_path}")


def export_active_model_to_abaqus(output_path=None):
    model = getApp().getActiveModel()
    if output_path is None:
        output_path = _default_output_path(model)
    export_model_to_abaqus(model, output_path)


if __name__ == "__main__":
    export_active_model_to_abaqus(DEFAULT_OUTPUT_PATH)
