from model import *

import os


# Set this to an explicit path if you do not want the default "<model>.inp".
DEFAULT_OUTPUT_PATH = None


PLANE_STRESS_2D = 0
PLANE_STRAIN_2D = 1
AXISYMMETRIC_2D = 2
SOLID_3D = 3


def _safe_part_name(part, fallback_index):
    name = part.getName()
    if name:
        cleaned = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name.strip())
        if cleaned:
            return cleaned
    return f"Part_{fallback_index}"


def _default_output_path(model):
    model_path = ""
    try:
        model_path = model.getFilePath()
    except Exception:
        model_path = ""

    if model_path:
        stem, _ = os.path.splitext(model_path)
        return stem + ".inp"

    model_name = model.getName() or "model"
    stem, _ = os.path.splitext(model_name)
    if not stem:
        stem = "model"
    return os.path.abspath(stem + ".inp")


def _element_type_for_part(model, mesh, node_count):
    analysis_type = model.getAnalysisType()
    mesh_dim = mesh.getDim()

    if node_count == 2:
        return "T2D2" if mesh_dim == 2 else "T3D2"

    if analysis_type == PLANE_STRESS_2D:
        if node_count == 3:
            return "CPS3"
        if node_count == 4:
            return "CPS4"
    elif analysis_type == PLANE_STRAIN_2D:
        if node_count == 3:
            return "CPE3"
        if node_count == 4:
            return "CPE4"
    elif analysis_type == AXISYMMETRIC_2D:
        if node_count == 3:
            return "CAX3"
        if node_count == 4:
            return "CAX4"
    else:
        if node_count == 4:
            return "C3D4"
        if node_count == 6:
            return "C3D6"
        if node_count == 8:
            return "C3D8"

    raise ValueError(
        f"Unsupported Abaqus element mapping: analysisType={analysis_type}, "
        f"meshDim={mesh_dim}, nodesPerElement={node_count}"
    )


def export_model_to_abaqus(model, output_path):
    if model is None:
        raise RuntimeError("No active model available")

    output_path = os.path.abspath(output_path)
    output_dir = os.path.dirname(output_path)
    if output_dir and not os.path.isdir(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    with open(output_path, "w", encoding="ascii") as out:
        out.write("*HEADING\n")
        out.write("WeldFormGUI export to Abaqus\n")
        out.write("** Generated by scripts/export_abaqus.py\n")

        exported_part_names = []

        for part_index in range(model.getPartCount()):
            part = model.getPart(part_index)
            if part is None or part.getMesh() is None:
                continue

            mesh = part.getMesh()
            part_name = _safe_part_name(part, part_index)
            exported_part_names.append(part_name)

            out.write(f"**\n** PART: {part_name}\n**\n")
            out.write(f"*PART, NAME={part_name}\n")
            out.write("*NODE\n")

            node_label_by_id = {}
            for node_index in range(mesh.getNodeCount()):
                node = mesh.getNode(node_index)
                label = node_index + 1
                node_label_by_id[node.getId()] = label
                out.write(
                    f"{label}, {node.getPos(0):.16g}, {node.getPos(1):.16g}, {node.getPos(2):.16g}\n"
                )

            elements_by_type = {}
            for elem_index in range(mesh.getElemCount()):
                elem = mesh.getElem(elem_index)
                elem_type = _element_type_for_part(model, mesh, elem.getNodeCount())
                connectivity = []
                for local_node in range(elem.getNodeCount()):
                    node_id = elem.getNodeId(local_node)
                    if node_id not in node_label_by_id:
                        raise KeyError(
                            f"Element {elem_index + 1} references unknown node id {node_id}"
                        )
                    connectivity.append(node_label_by_id[node_id])
                elements_by_type.setdefault(elem_type, []).append((elem_index + 1, connectivity))

            for elem_type, elements in elements_by_type.items():
                out.write(f"*ELEMENT, TYPE={elem_type}\n")
                for elem_label, connectivity in elements:
                    conn_str = ", ".join(str(value) for value in connectivity)
                    out.write(f"{elem_label}, {conn_str}\n")

            out.write("*END PART\n")

        out.write("**\n** ASSEMBLY\n**\n")
        out.write("*ASSEMBLY, NAME=Assembly\n")
        for part_name in exported_part_names:
            out.write(f"*INSTANCE, NAME={part_name}-1, PART={part_name}\n")
            out.write("*END INSTANCE\n")
        out.write("*END ASSEMBLY\n")

    print(f"Abaqus export written to: {output_path}")


def export_active_model_to_abaqus(output_path=None):
    model = getApp().getActiveModel()
    if output_path is None:
        output_path = _default_output_path(model)
    export_model_to_abaqus(model, output_path)


if __name__ == "__main__":
    export_active_model_to_abaqus(DEFAULT_OUTPUT_PATH)
