#!/usr/bin/env bash

export WELDFORM_SOLVER_EDITION=std
export WELDFORM_STD_NODE_LIMIT="${WELDFORM_STD_NODE_LIMIT:-500}"
export WELDFORM_STD_ALLOW_THERMAL="${WELDFORM_STD_ALLOW_THERMAL:-0}"

echo "WELDFORM_SOLVER_EDITION=${WELDFORM_SOLVER_EDITION}"
echo "WELDFORM_STD_NODE_LIMIT=${WELDFORM_STD_NODE_LIMIT}"
echo "WELDFORM_STD_ALLOW_THERMAL=${WELDFORM_STD_ALLOW_THERMAL}"
echo
echo "Run with:"
echo "  source scripts/use_solver_std.sh"
